name: Build CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[cpu,dev]"

      - name: Run tests
        run: pytest -q

      - name: Build distributions
        run: python -m build

      - name: Create Colab bundle (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\scripts\win\make_colab_bundle.ps1

      - name: Create Colab bundle (Unix)
        if: runner.os != 'Windows'
        run: bash scripts/make_colab_bundle.sh

      - name: Upload Colab bundle
        uses: actions/upload-artifact@v4
        with:
          name: colab-bundle-${{ runner.os }}-py${{ matrix.python-version }}
          path: dist/colab_bundle.zip
